// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"
	"go-cqrs-chat-example/dto"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAaaRestClient creates a new instance of MockAaaRestClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAaaRestClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAaaRestClient {
	mock := &MockAaaRestClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAaaRestClient is an autogenerated mock type for the AaaRestClient type
type MockAaaRestClient struct {
	mock.Mock
}

type MockAaaRestClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAaaRestClient) EXPECT() *MockAaaRestClient_Expecter {
	return &MockAaaRestClient_Expecter{mock: &_m.Mock}
}

// GetUsers provides a mock function for the type MockAaaRestClient
func (_mock *MockAaaRestClient) GetUsers(ctx context.Context, userIds []int64) ([]*dto.User, error) {
	ret := _mock.Called(ctx, userIds)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*dto.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]*dto.User, error)); ok {
		return returnFunc(ctx, userIds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []*dto.User); ok {
		r0 = returnFunc(ctx, userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, userIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAaaRestClient_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockAaaRestClient_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userIds []int64
func (_e *MockAaaRestClient_Expecter) GetUsers(ctx interface{}, userIds interface{}) *MockAaaRestClient_GetUsers_Call {
	return &MockAaaRestClient_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, userIds)}
}

func (_c *MockAaaRestClient_GetUsers_Call) Run(run func(ctx context.Context, userIds []int64)) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAaaRestClient_GetUsers_Call) Return(users []*dto.User, err error) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockAaaRestClient_GetUsers_Call) RunAndReturn(run func(ctx context.Context, userIds []int64) ([]*dto.User, error)) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchGetUsers provides a mock function for the type MockAaaRestClient
func (_mock *MockAaaRestClient) SearchGetUsers(c context.Context, searchString string, including bool, ids []int64, page int, size int) ([]*dto.User, int, error) {
	ret := _mock.Called(c, searchString, including, ids, page, size)

	if len(ret) == 0 {
		panic("no return value specified for SearchGetUsers")
	}

	var r0 []*dto.User
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, []int64, int, int) ([]*dto.User, int, error)); ok {
		return returnFunc(c, searchString, including, ids, page, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, []int64, int, int) []*dto.User); ok {
		r0 = returnFunc(c, searchString, including, ids, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, []int64, int, int) int); ok {
		r1 = returnFunc(c, searchString, including, ids, page, size)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, bool, []int64, int, int) error); ok {
		r2 = returnFunc(c, searchString, including, ids, page, size)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAaaRestClient_SearchGetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchGetUsers'
type MockAaaRestClient_SearchGetUsers_Call struct {
	*mock.Call
}

// SearchGetUsers is a helper method to define mock.On call
//   - c context.Context
//   - searchString string
//   - including bool
//   - ids []int64
//   - page int
//   - size int
func (_e *MockAaaRestClient_Expecter) SearchGetUsers(c interface{}, searchString interface{}, including interface{}, ids interface{}, page interface{}, size interface{}) *MockAaaRestClient_SearchGetUsers_Call {
	return &MockAaaRestClient_SearchGetUsers_Call{Call: _e.mock.On("SearchGetUsers", c, searchString, including, ids, page, size)}
}

func (_c *MockAaaRestClient_SearchGetUsers_Call) Run(run func(c context.Context, searchString string, including bool, ids []int64, page int, size int)) *MockAaaRestClient_SearchGetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 []int64
		if args[3] != nil {
			arg3 = args[3].([]int64)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAaaRestClient_SearchGetUsers_Call) Return(users []*dto.User, n int, err error) *MockAaaRestClient_SearchGetUsers_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *MockAaaRestClient_SearchGetUsers_Call) RunAndReturn(run func(c context.Context, searchString string, including bool, ids []int64, page int, size int) ([]*dto.User, int, error)) *MockAaaRestClient_SearchGetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatCreateOption creates a new instance of MockChatCreateOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatCreateOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatCreateOption {
	mock := &MockChatCreateOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatCreateOption is an autogenerated mock type for the ChatCreateOption type
type MockChatCreateOption struct {
	mock.Mock
}

type MockChatCreateOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatCreateOption) EXPECT() *MockChatCreateOption_Expecter {
	return &MockChatCreateOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockChatCreateOption
func (_mock *MockChatCreateOption) Apply(chatCreateDto *dto.ChatCreateDto) {
	_mock.Called(chatCreateDto)
	return
}

// MockChatCreateOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockChatCreateOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - chatCreateDto *dto.ChatCreateDto
func (_e *MockChatCreateOption_Expecter) Apply(chatCreateDto interface{}) *MockChatCreateOption_Apply_Call {
	return &MockChatCreateOption_Apply_Call{Call: _e.mock.On("Apply", chatCreateDto)}
}

func (_c *MockChatCreateOption_Apply_Call) Run(run func(chatCreateDto *dto.ChatCreateDto)) *MockChatCreateOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.ChatCreateDto
		if args[0] != nil {
			arg0 = args[0].(*dto.ChatCreateDto)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatCreateOption_Apply_Call) Return() *MockChatCreateOption_Apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatCreateOption_Apply_Call) RunAndReturn(run func(chatCreateDto *dto.ChatCreateDto)) *MockChatCreateOption_Apply_Call {
	_c.Run(run)
	return _c
}

// NewMockChatGetOption creates a new instance of MockChatGetOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatGetOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatGetOption {
	mock := &MockChatGetOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatGetOption is an autogenerated mock type for the ChatGetOption type
type MockChatGetOption struct {
	mock.Mock
}

type MockChatGetOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatGetOption) EXPECT() *MockChatGetOption_Expecter {
	return &MockChatGetOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockChatGetOption
func (_mock *MockChatGetOption) Apply(queryParams *url.Values) *url.Values {
	ret := _mock.Called(queryParams)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *url.Values
	if returnFunc, ok := ret.Get(0).(func(*url.Values) *url.Values); ok {
		r0 = returnFunc(queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.Values)
		}
	}
	return r0
}

// MockChatGetOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockChatGetOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - queryParams *url.Values
func (_e *MockChatGetOption_Expecter) Apply(queryParams interface{}) *MockChatGetOption_Apply_Call {
	return &MockChatGetOption_Apply_Call{Call: _e.mock.On("Apply", queryParams)}
}

func (_c *MockChatGetOption_Apply_Call) Run(run func(queryParams *url.Values)) *MockChatGetOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.Values
		if args[0] != nil {
			arg0 = args[0].(*url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatGetOption_Apply_Call) Return(values *url.Values) *MockChatGetOption_Apply_Call {
	_c.Call.Return(values)
	return _c
}

func (_c *MockChatGetOption_Apply_Call) RunAndReturn(run func(queryParams *url.Values) *url.Values) *MockChatGetOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageCreateOption creates a new instance of MockMessageCreateOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageCreateOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageCreateOption {
	mock := &MockMessageCreateOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageCreateOption is an autogenerated mock type for the MessageCreateOption type
type MockMessageCreateOption struct {
	mock.Mock
}

type MockMessageCreateOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageCreateOption) EXPECT() *MockMessageCreateOption_Expecter {
	return &MockMessageCreateOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockMessageCreateOption
func (_mock *MockMessageCreateOption) Apply(messageCreateDto *dto.MessageCreateDto) {
	_mock.Called(messageCreateDto)
	return
}

// MockMessageCreateOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockMessageCreateOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - messageCreateDto *dto.MessageCreateDto
func (_e *MockMessageCreateOption_Expecter) Apply(messageCreateDto interface{}) *MockMessageCreateOption_Apply_Call {
	return &MockMessageCreateOption_Apply_Call{Call: _e.mock.On("Apply", messageCreateDto)}
}

func (_c *MockMessageCreateOption_Apply_Call) Run(run func(messageCreateDto *dto.MessageCreateDto)) *MockMessageCreateOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.MessageCreateDto
		if args[0] != nil {
			arg0 = args[0].(*dto.MessageCreateDto)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageCreateOption_Apply_Call) Return() *MockMessageCreateOption_Apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMessageCreateOption_Apply_Call) RunAndReturn(run func(messageCreateDto *dto.MessageCreateDto)) *MockMessageCreateOption_Apply_Call {
	_c.Run(run)
	return _c
}

// NewMockMessageGetOption creates a new instance of MockMessageGetOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageGetOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageGetOption {
	mock := &MockMessageGetOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageGetOption is an autogenerated mock type for the MessageGetOption type
type MockMessageGetOption struct {
	mock.Mock
}

type MockMessageGetOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageGetOption) EXPECT() *MockMessageGetOption_Expecter {
	return &MockMessageGetOption_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockMessageGetOption
func (_mock *MockMessageGetOption) Apply(queryParams *url.Values) *url.Values {
	ret := _mock.Called(queryParams)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *url.Values
	if returnFunc, ok := ret.Get(0).(func(*url.Values) *url.Values); ok {
		r0 = returnFunc(queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.Values)
		}
	}
	return r0
}

// MockMessageGetOption_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockMessageGetOption_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - queryParams *url.Values
func (_e *MockMessageGetOption_Expecter) Apply(queryParams interface{}) *MockMessageGetOption_Apply_Call {
	return &MockMessageGetOption_Apply_Call{Call: _e.mock.On("Apply", queryParams)}
}

func (_c *MockMessageGetOption_Apply_Call) Run(run func(queryParams *url.Values)) *MockMessageGetOption_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.Values
		if args[0] != nil {
			arg0 = args[0].(*url.Values)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageGetOption_Apply_Call) Return(values *url.Values) *MockMessageGetOption_Apply_Call {
	_c.Call.Return(values)
	return _c
}

func (_c *MockMessageGetOption_Apply_Call) RunAndReturn(run func(queryParams *url.Values) *url.Values) *MockMessageGetOption_Apply_Call {
	_c.Call.Return(run)
	return _c
}
