// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"
	"go-cqrs-chat-example/dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAaaRestClient creates a new instance of MockAaaRestClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAaaRestClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAaaRestClient {
	mock := &MockAaaRestClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAaaRestClient is an autogenerated mock type for the AaaRestClient type
type MockAaaRestClient struct {
	mock.Mock
}

type MockAaaRestClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAaaRestClient) EXPECT() *MockAaaRestClient_Expecter {
	return &MockAaaRestClient_Expecter{mock: &_m.Mock}
}

// GetUsers provides a mock function for the type MockAaaRestClient
func (_mock *MockAaaRestClient) GetUsers(ctx context.Context, userIds []int64) ([]dto.User, error) {
	ret := _mock.Called(ctx, userIds)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []dto.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) ([]dto.User, error)); ok {
		return returnFunc(ctx, userIds)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) []dto.User); ok {
		r0 = returnFunc(ctx, userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(ctx, userIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAaaRestClient_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockAaaRestClient_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userIds []int64
func (_e *MockAaaRestClient_Expecter) GetUsers(ctx interface{}, userIds interface{}) *MockAaaRestClient_GetUsers_Call {
	return &MockAaaRestClient_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, userIds)}
}

func (_c *MockAaaRestClient_GetUsers_Call) Run(run func(ctx context.Context, userIds []int64)) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAaaRestClient_GetUsers_Call) Return(users []dto.User, err error) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockAaaRestClient_GetUsers_Call) RunAndReturn(run func(ctx context.Context, userIds []int64) ([]dto.User, error)) *MockAaaRestClient_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}
