// Code generated by MockGen. DO NOT EDIT.
// Source: aaa.go
//
// Generated by this command:
//
//	mockgen -source=aaa.go -destination mock/lock.go
//

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	dto "go-cqrs-chat-example/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAaaRestClient is a mock of AaaRestClient interface.
type MockAaaRestClient struct {
	ctrl     *gomock.Controller
	recorder *MockAaaRestClientMockRecorder
	isgomock struct{}
}

// MockAaaRestClientMockRecorder is the mock recorder for MockAaaRestClient.
type MockAaaRestClientMockRecorder struct {
	mock *MockAaaRestClient
}

// NewMockAaaRestClient creates a new mock instance.
func NewMockAaaRestClient(ctrl *gomock.Controller) *MockAaaRestClient {
	mock := &MockAaaRestClient{ctrl: ctrl}
	mock.recorder = &MockAaaRestClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAaaRestClient) EXPECT() *MockAaaRestClientMockRecorder {
	return m.recorder
}

// GetUsers mocks base method.
func (m *MockAaaRestClient) GetUsers(ctx context.Context, userIds []int64) ([]dto.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, userIds)
	ret0, _ := ret[0].([]dto.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockAaaRestClientMockRecorder) GetUsers(ctx, userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockAaaRestClient)(nil).GetUsers), ctx, userIds)
}
