package dto

const EventTypeChatCreated = "chat_created"
const EventTypeChatEdited = "chat_edited"
const EventTypeChatDeleted = "chat_deleted"
const EventTypeChatRedraw = "chat_redraw"
const EventTypeParticipantAdded = "participant_added"
const EventTypeParticipantDeleted = "participant_deleted"
const EventTypeParticipantEdited = "participant_edited"
const EventTypeMessageCreated = "message_created"
const EventTypeHasUnreadMessagesChanged = "has_unread_messages_changed"
const EventTypeChatUnreadMessagesChanged = "chat_unread_messages_changed"
const EventTypeMessageEdited = "message_edited"
const EventTypeMessageDeleted = "message_deleted"
const EventTypeMessageBroadCast = "user_broadcast"
const EventTypeMessageType = "user_typing"
const EventTypeReactionChanged = "reaction_changed"
const EventTypeReactionRemoved = "reaction_removed"

const EventTypeParticipantChanged = "participant_changed"
const EventTypeMessagesReload = "messages_reload"
const EventTypeParticipantsReload = "participants_reload"
